# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeitem',
            name='tags',
            field=models.CharField(blank=True, max_length=2047),
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='description',
            field=models.TextField(blank=True, max_length=2047),
        ),
    ]
