# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 23:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_resumes(apps, schema_editor):
    Resume = apps.get_model('resume', 'Resume')
    ResumeItem = apps.get_model('resume', 'ResumeItem')
    User = apps.get_model('auth', 'User')

    for user in User.objects.all():
        ris = ResumeItem.objects.filter(user=user)
        if ris.exists():
            default_resume = Resume.objects.create(
                user=user,
                name="Default"
            )
            ris.update(resume=default_resume)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0003_resume'),
    ]

    operations = [
        migrations.RunPython(create_default_resumes)
    ]
