# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-28 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_create_initial_resumes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='resumeitem',
            name='resume',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='resume.Resume'
            ),
        ),
    ]
